apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: ingest-circuit-bronze
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "docker.io/kauan4453/spark-operator:v3.1.1"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/ingest-circuits.py"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
